spring.application.name=bank-api

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# H2 Console (only active in local profile)
spring.h2.console.enabled=false

# Server
server.port=8080

# CORS
cors.allowed-origins=http://localhost:4200

# External log
external.log.url=https://httpstat.us/200
external.log.timeout-ms=3000