spring.application.name=bank-api

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console (only active in local profile)
spring.h2.console.enabled=false

# Server
# Use PORT env var if provided by Railway / PaaS, fallback to 8080
server.port=${PORT:8080}

# CORS
cors.allowed-origins=http://localhost:4200

# External log
external.log.url=https://httpstat.us/200
external.log.timeout-ms=3000

# Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.operationsSorter=method
